name: Auto Reply to New Issues

on:
  issues:
    types: [opened]

jobs:
  auto-reply:
    runs-on: ubuntu-latest
    steps:
      - name: Post auto-reply comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            👋 Automated Notice — GitHub Interact Team
This issue has been flagged for closure due to inactivity.
Our support team at **GitHub Interact** will guide you step by step until the issue is fully resolved.  

            For faster help, or would like priority troubleshooting, please contact us at:
            - email: <mailto:GitHub.interact@gmail.com>
            - Or Visit the Web Support page: https://git-cryptoresolvehub.web.app/

            We will triage this issue shortly.
- GitHub Interact Team 🚀
